### ISSUE TITLE
Crash with rhythmbox v2.7

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#1]
The webupd8 maintainer has noticed the following error when using your plugin:

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
      import gobject._gobject
    Traceback (most recent call last):
      File "/usr/lib/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 26, in <module>
        from LastFMExtensionGui import ConfigDialog
      File "/usr/lib/rhythmbox/plugins/lastfm_extension/LastFMExtensionGui.py", line 36, in <module>
        class ConfigDialog( GObject.Object, PeasGtk.Configurable ):
      File "/usr/lib/rhythmbox/plugins/lastfm_extension/LastFMExtensionGui.py", line 38, in ConfigDialog
        object = GObject.property(type=GObject.Object)
      File "/usr/lib/python2.7/dist-packages/gi/_gobject/propertyhelper.py", line 109, in __init__
        self.type = self._type_from_python(type)
      File "/usr/lib/python2.7/dist-packages/gi/_gobject/propertyhelper.py", line 230, in _type_from_python
        raise TypeError("Unsupported type: %r" % (type_,))
    TypeError: Unsupported type: <type 'gobject.GObject'>

I'm wondering - do you think it's because of the use of the legacy "import rb" in LastFMExtensionGui.py instead of using RB from "from gi.repository"?

**Comment by asermax** [comment]
I'm not sure, that import rb is actually for importing the rb plugin (a base plugin that have some functionality to be used by other plugins), so it shouldn't cause any problem. But maybe it's deprecated too, so I will checkout what the problem could be.
Thanks for the report, if you find something else, let me know.

**Comment by asermax** [comment]
For what I have been reading, using the rb plugin shouldn't cause any problem. 
I have no clue what could be causing the error, since it's working alright in my box. 
Could you give me a little more information about how the error occurs? Some info on your system might help too. And if you are up to it, try activating some other plugins on Rhythmbox and Totem (both use the same plugin engine) to see if something else triggers the same error.

**Comment by fossfreedom** [comment]
I think you are correct - the guy was playing with a number of plugins - I dont think the issue is with yours.  I'll close this one.  Thanks again.
