### ISSUE TITLE
fingerprint song - no matches found

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#11]
It doesnt matter what song I pick I cant seem to get any lastfm matches - just returns "no matches found".

Any advice what I should need to add to the code (and where) to diagnose what is being sent to lastfm and what is being returned?

**Comment by asermax** [comment]
You can add some print statements on the _match method in the LastFMFingerprinter class. The only relevant parameter is the file path, since the others are just to feed last.fm database. After the try/catch, you can print the fpid (fingerprint) and result variables to see what happened. If fpid isn't declared, is because the matcher failed horribly; result can be either a list of Tracks instances (good) or a Exception (bad).

Something to take into account: the matcher is called in another process 'coz rhythmbox threading model wouldn't let me use it as an imported module. You can test it separatedly as an standalone script. The command would be 'matcher.py "path" "artist" "album" "title"'. 

Let me know if i can help you with something else :3

**Comment by fossfreedom** [comment]
ok - code modified as

try:  
            fpid = check_output( 
                        [self.matcher_path, "%s" % path, artist, album, title] )

```
        print "fpid"
        print fpid 
        result = network.get_tracks_by_fpid( fpid )

        print "returned"

    except CalledProcessError as error:
        #in the case the fingerprinter fails, raise an exception 
        print "error"
        print error.output
        raise Exception( error.output )

    print "result"        
    print result

    return result
```

with the results:

rhythmbox -D LastFMExtensionFingerprinter
(21:39:26) [0x99a32c0] [LastFMFingerprinter._match] LastFMExtensionFingerprinter.py:339: /home/dad/Music/All Saints - All Saints/04 - All Saints - Under The Bridge.ogg
(21:39:26) [0x99a32c0] [LastFMFingerprinter._match] LastFMExtensionFingerprinter.py:340: All Saints
(21:39:26) [0x99a32c0] [LastFMFingerprinter._match] LastFMExtensionFingerprinter.py:341: All Saints
(21:39:26) [0x99a32c0] [LastFMFingerprinter._match] LastFMExtensionFingerprinter.py:342: Under the Bridge
(21:39:30) [0x99a32c0] [LastFMFingerprinter._match] LastFMExtensionFingerprinter.py:349: fpid
(21:39:30) [0x99a32c0] [LastFMFingerprinter._match] LastFMExtensionFingerprinter.py:350: 629603

(rhythmbox:10747): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.32.3/./gobject/gsignal.c:2572: instance `0x8cae0b8' has no handler with id`7410'

(rhythmbox:10747): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.32.3/./gobject/gsignal.c:2572: instance `0x8cae0b8' has no handler with id`7411'

it looks like its going into network.get_tracks_by_fpid but I dont see a result coming from it so Its getting stuck there?

The two signal.c errors you see is when you close Rhythmbox - only appears with lastfm-extension.

scratching my head on this one!

**Comment by asermax** [comment]
Oh sorry, I was wrong about result, if there's an exception, it's thrown into the callback responsible of dealing with the result.
Try adding 'print result' in the beginning of the '_append_options' method, that should print thee Exception. It should be the same error you get in the dialog, but maybe it can give us more info about it.

**Comment by fossfreedom** [comment]
ok - thanks

print result immediately after _append_options gives

(21:59:54) [0xa588580] [LastFMFingerprinter._append_options] LastFMExtensionFingerprinter.py:411: 'NoneType' object has no attribute 'get_tracks_by_fpid'

**Comment by asermax** [comment]
Hmmm it seems like the network isn't created...? You should checkout a couple of things:
- If the network is actually initialized in the 'connection_changed' method in the lastfm_extension.py module. A 'print self.network' at the end should give you an idea.
- If the networks is correctly assigned to the fingerprinting extension in the LastFMFingerprinter **init** method. Add a 'print self.network' after the asigment.
  If one is an actual LastFMNetwork and the other is None, there is something happening in the middle. If both are None, there's a problem initializing the network :/

**Comment by fossfreedom** [comment]
ok - in the "def conection_changed" method its going straight into the else clause so settings[key] is "false"

I printed "settings" and "key" if this helps at the beginning of "conection_changed":

(22:25:51) [0x909bea0] [LastFMExtensionPlugin.conection_changed] lastfm_extension.py:787: `<Settings object at 0x9b9dfcc (GSettings at 0x962b6c8)>`
(22:25:51) [0x909bea0] [LastFMExtensionPlugin.conection_changed] lastfm_extension.py:788: connected

**Comment by asermax** [comment]
I found the problem! I forgot to check if the 'connected' setting was enabled before creating the fingerprinter. 
You should be connected with your user before using the fingerprinter (it doesn't use your user for the initial fingerprinting, but it does for the extra info, so to make it simple, it won't work when you are not logged with your last.fm account).

Thanks you again foss, for helping me find this bug d:
Let me know if it works now, the fingerprinter shouldn't be enabled until you login!

**Comment by fossfreedom** [comment]
ok - you are quite correct - for whatever reason the lastfm was not logged in but the fingerprint box was checked.

I do note that you can check this box without logging in - but anyway.

With the box checked,but not logged in - no fingerprint menu option.

As soon as I login - fingerprint menu option is visible and it returns matches correctly.

Great!  Thank-you!

**Comment by asermax** [comment]
I'll add a note clarifying that you need to be logged before using the extras into the README for future reference.

Glad it worked :]
