### ISSUE TITLE
Last.FM changing protocol??

### ISSUE THREAD

**Issue by EdeZeeuw** [asermax/lastfm_extension#13]
# Last.FM is changing Streaming-protocol.

I only use your extention in Rhythmbox to listen to the radio streams.

Is your plugin already working with the new protocol?

This is the message i received:
# 

Hello, DJ-EAZ.

We're writing you to let you know that there will soon be a change to Last.fm radio that may affect you. Our stats show that you've listened to radio through an application that uses our old streaming protocol. On 1 December we will deprecate this old protocol, so in some applications radio will no longer work.

If you would like to continue enjoying Last.fm Radio, consider upgrading to a new application or using http://www.last.fm/listen

Thanks,
The Last.fm Team

Last.fm Ltd, Karen House, 1–11 Baches Street, London, UK, N1 6DL

**Comment by asermax** [comment]
Actually my extension doesn't work with radio streams, you may be talking about the built-in LastFM plugin that comes with Rhythmbox.
Someone else asked me a similar question, and as I said to him, I'm not sure what this could mean. Most likely, the plugin would break in the near future until the Rhythmbox developers adapt it to the new protocol.
I think you would get a more precise answer if you post your question on the rhythmbox issue tracker, that's located on [bugzilla](https://bugzilla.gnome.org/buglist.cgi?quicksearch=keywords%3Agnome-love+product%3A%22rhythmbox%22+).
