### ISSUE TITLE
ability to distinguish between tracks in different albums

### ISSUE THREAD

**Issue by dror3go** [asermax/lastfm_extension#15]
In cases where a music library includes two tracks by the same name and by the same artist, each from a different album, the playcount gathered by the extension will be the same.

It it possible to implement distinguish between albums using last.fm's API?

**Comment by asermax** [comment]
Nop, as far as I know LastFM identifies a track by it's name and artist, and the same track may have one or more albums asociated to it.
The [track.search](http://www.last.fm/api/show/track.search) API call only allows the track name and track artist to make the search itself.
I'll check if there's a way, I'll let you know either way.

**Comment by asermax** [comment]
After checking, seems like my last statement is true. I can't differentiate tracks from different albums since LastFM doesn't do it either u_u
