### ISSUE TITLE
Rhytmbox is crashing when choosing preferences

### ISSUE THREAD

**Issue by austris-argalis** [asermax/lastfm_extension#20]
Whenever I try to select preferences of lastfm extension - rhytmbox crashes.
Im using fedora 17, installation made me some headache, but I think I have installed all dependencies. Here is an error I get when start rhytmbox from terminal :

```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfm_extension-master/lastfm_extension.py", line 419, in do_activate
    LastFMExtensionUtils.init(rb.find_plugin_file(self, LASTFM_ICON))
  File "/usr/lib/rhythmbox/plugins/lastfm_extension-master/LastFMExtensionUtils.py", line 38, in init
    icon = GdkPixbuf.Pixbuf.new_from_file(icon_path)
  File "/usr/lib/python2.7/site-packages/gi/types.py", line 72, in constructor
    return info.invoke(cls, *args, **kwargs)
TypeError: Argument 0 does not allow None as a value
```

and here is an error I get when choose preferences of plugin : 

```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfm_extension-master/LastFMExtensionGui.py", line 55, in do_create_configure_widget
    self.settings = LastFMExtensionBag.get_instance().settings.get_section(
AttributeError: 'NoneType' object has no attribute 'settings'
Segmentation fault (core dumped)
```

Hope you can help. :)

**Comment by asermax** [comment]
A couple of questions to try to pinpoint the problem:
- Which version of Rhythmbox are you using?
- Are you installing the plugin directly from this repository are you using a pre-packaged version of the plugin?
- In the case you are using the installation script found on this repository, are you installing the plugin locally or globally? In the case you are installing it globally, could you try removing it (deleting the plugin folder on `/usr/lib/rhyhtmbox/plugins`) and try installing it locally?

The second error is probably a consequence of the first one. I have an idea of what may be causing the first one, but I'm not enterily sure, so this extra info may help me confirm it.
Btw, thanks for informing me about this problem through here :]

**Comment by austris-argalis** [comment]
Yey, I solved the problem! :)
Rhytmbox version is 2.97 and I was not using pre-packed version of the plugin.
My mistake was that I manually placed plugin folder in "usr/lib/rhythmbox/plugins" and also installed it locally.
Thanks for the answer, without you i would not realize that "/usr/lib/rhyhtmbox/plugins" directory is for global plugins!

**Comment by asermax** [comment]
Great! Glad to help :]
