### ISSUE TITLE
Core dump on enabling plugin (GLib-GIO-ERROR)

### ISSUE THREAD

**Issue by bartensud** [asermax/lastfm_extension#3]
Hi,
after installing via install.sh I wanted to enable lastfm_extension plugin in Rhythmbox. When I enabled the checkbox, Rhythmbox crashed.

If I start Rhythmbox in debug mode it crashes every time ending up with:
(rhythmbox:4620): GLib-GIO-ERROR **: Settings schema 'org.gnome.rhythmbox.plugins.lastfm_extension' is not installed
Trace/breakpoint trap (core dumped)

I checked if the installation of the glib schemas worked and found following files in ~/.local/share/glib-2.0/schemas:
- gschemas.compiled
- org.gnome.rhythmbox.plugins.lastfm_extension.gschema.xml
  I'm not familiar with glib schemas. So, I'm not sure if this is fine or how to check if it is.

I'm using Ubuntu 12.04 (64 bit).

Thanks for your support.

**Comment by asermax** [comment]
Hi and thanks for the feedback!
Apparently glib doesn't accept local schema installation; when I tested it, I forgot to remove the global schema I had previously used, avoiding the crash altogether.
I'll be pushing a fixed install script which will install the schema globally. To do that, it will have to ask for administrative access (the global glib-schema path is inside /usr/share).

Please test it out and let me know if it works!

**Comment by bartensud** [comment]
It works. Thanks a lot!!!
