### ISSUE TITLE
Playing a song in Rhythmbox v2.97 breaks stars rating when being offline

### ISSUE THREAD

**Issue by lucidlynx82** [asermax/lastfm_extension#4]
Playing a song in Rhythmbox v2.97 breaks stars rating when being offline.

I've found that bug because I'm a user of the song's rating system in Rhythmbox since the beginning of 2012.

When I was at work today, which I never go online with their wifi network, I was trying to rate some of my new songs in my 
music collection and found that whenever I was clicking on the song ... it went from being no stars rating to 5 stars rating without
my inputs !!

So, I've remembered that I added your superb rhythmbox extension, I went to my plugins menu and deactivated your last fm extension (by the way, I have the last.fm extension that comes with Rhythmbox originally, which is activated).

Remember that I'm still being offline, I started one of my song again and now it didn't chose 5 stars rating without my input !

So when being offline and your last.fm plugin activated, when you start a song in your collection with Rhythmbox 2.97 (and Ubuntu 12.04LTS with all the updates) and the other last.fm extension that comes with Rhythmbox originally ... each time you click a song it becomes a 5 stars song without your inputs ..!!

When online, this bug don't comes out ! ... 

Tks for trying to solve this bug ;)

**Comment by asermax** [comment]
Thank you very much for the report!
I'll see what is causing this bug and report back as soon as I can :3

**Comment by lucidlynx82** [comment]
In the meantime, it is disabled for now hehe, don't rush on this ;)

It is not a matter of life LOL

But I was happy to discover this bug ! My bug counts since being only on Ubuntu since the end of 2009 is now at like 15-20 hehe :)

Have a good night !

Tks for participating in the free world of Linux :) 

Date: Fri, 10 Aug 2012 21:00:25 -0700

**Comment by asermax** [comment]
Haha, finding bugs (and fixing them) it's kinda exciting, I agree d:

Well, I really didn't test the plugin in the 'being offline' scenario, so I found a bunch of bugs while testing out the one you found.
I fixed the issue with the rating, it should behave correctly now.
Also added an error message notification when trying to love/ban tracks while being offline.
I would appreciate if you could reinstall the plugin, test out the changes and give me some feedback!
And if you think this fixed your problem, feel free to mark the issue as closed.

Thanks again for the help :]

**Comment by lucidlynx82** [comment]
I got it from this link originally : http://www.webupd8.org/2012/08/rhythmbox-third-party-plugins-ubuntu-ppa.html#more

By adding a PPA : 
ppa:fossfreedom/rhythmbox-plugins in my Ubuntu 12.04LTS Linux distribution

I'm looking forward to test your new version :) Didn't know you were that fast in correcting
bugs LOL

Just one thing ... how should I update it (it was installed from a PPA) ?

In the meantime, i will look on your github to find the new version :)

Date: Fri, 10 Aug 2012 21:53:23 -0700

**Comment by asermax** [comment]
Since I don't manage the PPA (I didn't even know my plugin was added into it until now actually, I feel honored xD), I can't update the plugin through there. You can try issuing a bug over there to let the owner know of the changes made on this repository.

Meanwhile, replacing the file "/usr/lib/rhythmbox/plugins/lastfm_extension/lastfm_extension.py" from your filesystem by the latest version of the "lastfm_extension.py" file on this repo (and restarting Rhythmbox) would 'patch' your plugin version with the changes I've made. You'll need root privileges to do that.

In case you don't know, you can download the latest version of the repo files from the "Zip" button, on the left-top corner under the "Code" tab.

Hope I was clear with my instructions (english isn't my first language :/) and please let me know if you have any other problem.

PS: heh, the plugin is pretty simple so pinning bugs isn't that hard. As long as I have some time to spare, I fix them pretty fast :]

**Comment by lucidlynx82** [comment]
Don't worry about your English by the way it is not my first language too (mine being French language) ! Hehe

Okay ... I've notified the PPA host about the bug and gave him a link of what happened ... blabla...

But before that, I've tried replacing only the .py file but didn't remember the way to do so in root with the Terminal .. (ooops, instead I saw that I had new mail lollll so .. ). I went removing the PPA and all that and the extension with sudo apt-get purge ... blabla ..

In the end I tried also executing the .sh but it gave me an error .. 

Anyway .. I did what you wrote about downloading the zip file the repo .. extracted it and started the sh script and it went like a charm :)

:) 

Okay here is my report about your bug correction work :

I'm offline and now it doesn't rate my song 5 stars as I start playing it :)
And also ... I've tried to click on love the track button being offline and it gave me a ubuntu overlay message with the connection error , so that thing is ok :)

Hope that when being online after .. loll i won't get my song banned after all like I clicked to do the tests loll .. Update : All is ok :) Yahoooo

Thanks a lot ... now it is the time for me to go get some sleep (Here it is 02:50 in the night, I live in Quebec province .. Eastern time -5:00, in Canada)

Date: Fri, 10 Aug 2012 23:14:03 -0700

**Comment by asermax** [comment]
I'm glad it worked out :] I'll mark this topic as closed then.
Feel free to report any other issue you may have through here!
It feels nice to know someone is using your little piece of soft you know? Heh

Well, I'm off to sleep too (4 am in Argentina, lol), thanks again and see ya around.
