### ISSUE TITLE
LastFM fingerprint library not found

### ISSUE THREAD

**Issue by afrancoto** [asermax/lastfm_extension#6]
When I try to enable the fingerprinter from the Preferences, i get the error in the title. What should I do?

**Comment by asermax** [comment]
You need to install an external python library called pylastfp. You can install it using [PyPi](http://pypi.python.org/pypi). You can find the instructions for this particular package [here](http://pypi.python.org/pypi/pylastfp/). 

I probably should explain the process better on the README xD
