### ISSUE TITLE
match_file error

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#7]
Traceback (most recent call last):
  File "/home/dad/.local/share/rhythmbox/plugins/lastfm_extension/matcher.py", line 33, in <module>
    fpid = lastfp.match_file( Keys.API_KEY, path, metadata={ 'artist':artist,
AttributeError: 'module' object has no attribute 'match_file'

ok - I installed pylast using this method:

sudo apt-get install libfftw3-dev libsamplerate0-dev

downloaded and extracted
https://github.com/downloads/sampsyo/pylastfp/pylastfp-0.2.tar.gz

compiled:
python setup.py install

This compile but threw and error since it didnt have rights to install to /usr/local...

then ran

sudo python setup.py install

this ran

This then allowed me to activate the finger print option in preferences.

**Comment by asermax** [comment]
That link points to an outdated version of pylastfp that doesn't include the function I use on the plugin (that is v0.2, my code is based in v0.6).
You should either clone the master git repo or install it using pypi to get the latest version.

**Comment by fossfreedom** [comment]
ok - I think you should make this clear in the readme - infact the pylast install is not obvious to "beginners"

Perhaps add the following:

"On debian based systems such as Ubuntu:

wget http://pypi.python.org/packages/source/p/pylastfp/pylastfp-0.6.tar.gz#md5=292946bd34f24f533029085e063d5155
tar -zxvf pylastfp-0.6.tar.gz
cd pylastfp

Now install some prerequisite packages;
sudo apt-get install pip libfftw3-dev libsamplerate0-dev

Now compile and install:

sudo pip install pylastfp

If you have previously installed pylastfp then:

sudo pip install pylastfp --upgrade
"

**Comment by asermax** [comment]
If you follow the link to pyfplast I put on the README, there are the instructions to install it from pypi.
You don't need to manually download the package, pypi does it for you; you do need to install the dev libraries for fftw and libsamplerate tho. 

Neverthless, I'll add some instructions since you are right, some people might have problems installing it :3
