### ISSUE TITLE
finger print dialog is too small

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#8]
Suggestion:

most songs the song title actually exceeds the initial dialog size.

Perhaps just have the title as "lastfm fingerprint" and have a label in the window for the song title and I presume this will wrap for a relatively long title.

**Comment by asermax** [comment]
The idea of putting the info on the title is to have an idea of what you are fingerprinting if for some reason you forgot (you got to the bathroom, starting doing something else, etc). Once the matches appear on the dialog, the whole dialog resizes anyway and you can see the text if you need.
So, for now, I don't think I will change it. I'll take into account tho :3
